sudo: false
dist: trusty

services:
- docker

language: bash

branches:
  only:
  - master

script:
  # Build X86 docker image
  - docker build -f ./Dockerfile -t erikdevries/transcoder .

after_success:
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

      docker tag erikdevries/transcoder erikdevries/transcoder:latest
      docker tag erikdevries/transcoder erikdevries/transcoder:$TRAVIS_BUILD_NUMBER
      docker push erikdevries/transcoder
    fi
