#!/usr/bin/with-contenv sh

mkdir -p /input/processed /input/unprocessable /output

SHELL=sh chokidar "/input/*.webm" -c "if [ '{event}' = 'add' ] || [ '{event}' = 'change' ]; then /convert.sh '{path}'; fi;" --polling